[tool.ruff]
line-length = 88
target-version = "py38"

select = [
    "A", # flake8-builtins
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "E",
    "ERA", # flake8-eradicate
    "EXE", # flake8-executable
    "F",
    "G", # flake8-logging-format
    "I", # isort
    "PIE", # flake8-pie
    "RUF", # Ruff
    "S", # bandit
    "UP", # pyupgrade
    "W",
]
